#!/bin/sh

set -e

init_script_error_handler()
{
	return 0
}

# Automatically added by dh_installinit/12.10ubuntu1
if [ -x "/etc/init.d/isc-dhcp-server" ]; then
	invoke-rc.d isc-dhcp-server stop || exit 1
fi
# End automatically added section
# Automatically added by dh_systemd_start/12.10ubuntu1
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop 'isc-dhcp-server6.service' >/dev/null || true
fi
# End automatically added section


exit 0
